-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER U RIGHT JOIN (SELECT *
                                  FROM USED_GOODS_BOARD
                                  WHERE STATUS = 'DONE') B
ON U.USER_ID = B.WRITER_ID
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE)