-- 코드를 입력하세요
SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, S.MAX_FAVORITES AS FAVORITES
FROM REST_INFO I, (SELECT FOOD_TYPE , MAX(FAVORITES) AS MAX_FAVORITES
                FROM REST_INFO
                GROUP BY FOOD_TYPE
                ORDER BY FAVORITES DESC) S
WHERE I.FOOD_TYPE = S.FOOD_TYPE AND I.FAVORITES = S.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC