-- 코드를 입력하세요
SELECT C.CAR_TYPE, COUNT(*) AS CARS
FROM (SELECT *
FROM CAR_RENTAL_COMPANY_CAR
WHERE FIND_IN_SET('통풍시트' , OPTIONS)
UNION
SELECT *
FROM CAR_RENTAL_COMPANY_CAR
WHERE FIND_IN_SET('열선시트' , OPTIONS)
UNION
SELECT *
FROM CAR_RENTAL_COMPANY_CAR
WHERE FIND_IN_SET('가죽시트' , OPTIONS)) C
GROUP BY C.CAR_TYPE
ORDER BY C.CAR_TYPE