-- 코드를 입력하세요
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F, (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
      FROM FOOD_PRODUCT 
      WHERE CATEGORY REGEXP ('과자|국|김치|식용유')
      GROUP BY CATEGORY) S
WHERE F.CATEGORY = S.CATEGORY AND F.PRICE = S.MAX_PRICE
ORDER BY F.PRICE DESC