-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, P.CATEGORY, P.TOTAL_SALES
FROM AUTHOR A RIGHT JOIN (SELECT B.BOOK_ID, CATEGORY, AUTHOR_ID, SUM(PRICE * SALES) AS TOTAL_SALES
                FROM BOOK B RIGHT JOIN BOOK_SALES S
               ON B.BOOK_ID = S.BOOK_ID
               WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
               GROUP BY AUTHOR_ID, CATEGORY) P
ON A.AUTHOR_ID = P.AUTHOR_ID
ORDER BY A.AUTHOR_ID, CATEGORY DESC